name: Build & Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Dump Environment
      run: env | sort

    - name: Build
      run: pwsh build.ps1 -Configuration Release

    - name: Push NuGet Packages
      run: find _artifacts -name \*.nupkg -and -not -name \*.symbols.nupkg -exec dotnet nuget push --source https://www.myget.org/F/latham/api/v2/package --api-key "${MYGET_PUSH_API_KEY}" {} \;
      env:
        MYGET_PUSH_API_KEY: ${{ secrets.MYGET_PUSH_API_KEY }}